baseURL = "http://localhost"
copyright = "© 2022 Georgi Chelenkov"
title = "Georgi Chelenkov"
#paginate = 10
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # This settings allows inlining <script> and <style> tags in markdown, 
      # which is useful and required to use Prism plugins, but may be dangerous 
      # if the content isn't trustworthy.
      unsafe = true

[imaging]
  # JPEG and WebP image processing quality, defaults to 75%
  quality = 90

[params]
  # dark or light, defaults to light
  defaultTheme = "dark"
  # gray red green yellow blue purple aqua orange, defaults to blue
  themeColor = "red"
  # soft medium hard, defaults to medium
  themeContrast = "hard"
  author = "Georgi Chelenkov"
  subtitle = "Software Engineer"
  description = "Georgi Chelenkov is a Senior Software Developer and computer enthusiast."

  [params.logo]
    text = "gchelenkov.com"
    url = "/"

  [params.prism]
    languages = [
      "markup",
      "css",
      "clike",
      "javascript",
      "bash",
      "csharp",
      "hcl",
      "ignore",
      "json",
      "markdown",
      "powershell",
      "toml",
      "yaml"
    ]
    plugins = [
      "normalize-whitespace",
      "toolbar",
      "copy-to-clipboard",
      "command-line"
    ]
  
  # By default, the theme creates resized versions of images ranging from 300 to
  # 700 pixels wide in increments of 100 pixels
  #[params.imageResize]
  #  min = 300
  #  max = 700
  #  increment = 100

  # Social share links for posts:
  #   - iconSuite: "simple-icon" or "tabler-icon"
  #   - iconName: name of the icon from the "iconSuite"
  #   - {url} placeholder for post .Permalink
  #   - {title} placeholder for post .Title
  # See  https://github.com/bradvin/social-share-urls for more format strings
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "facebook"
    formatString = "https://www.facebook.com/sharer.php?u={url}"
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "reddit"
    formatString = "https://reddit.com/submit?url={url}&title={title}"
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "twitter"
    formatString = "https://twitter.com/intent/tweet?url={url}&text={title}"
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "linkedin"
    formatString = "https://www.linkedin.com/sharing/share-offsite/?url={url}"
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "whatsapp"
    formatString = "whatsapp://send/?text={title}%20{url}"
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "tumblr"
    formatString = "https://www.tumblr.com/widgets/share/tool?canonicalUrl={url}&title={title}&caption={title}"
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "pinterest"
    formatString = "http://pinterest.com/pin/create/button/?url={url}"
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "ycombinator"
    formatString = "https://news.ycombinator.com/submitlink?u={url}&t={title}"
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "vk"
    formatString = "http://vk.com/share.php?url={url}&title={title}&comment={title}"
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "xing"
    formatString = "https://www.xing.com/spi/shares/new?url={url}"
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "telegram"
    formatString = "https://telegram.me/share/url?url={url}&text={title}"
  [[params.socialShare]]
    iconSuite = "tabler-icon"
    iconName = "mail"
    formatString = "mailto:?subject={title}&body={url}"

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 10
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
    weight = 20
  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/cv"
    weight = 30
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 40

[languages]
  [languages.en]
    languageName = "English"
    weight = 10
    [languages.en.params.jsonResume]
      present = "present"
  [languages.bg]
    languageName = "Български"
    weight = 20
    [languages.bg.params.jsonResume]
      present = "сега"

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = ["'self'", "'unsafe-inline'", "https://www.google-analytics.com"]
prefetchsrc = ["'self'"]